In [1]:
pip install mlxtend

Note: you may need to restart the kernel to use updated packages.

'C:\Users\PRATIK' is not recognized as an internal or external command,
operable program or batch file.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('C:/Users/PRATIK JADHAV/Desktop/DSpratik/kaggle projects/Recommendation system/GroceryStoreDataSet.csv',names=['products'],header=None)

In [4]:
df

                          products
0               MILK,BREAD,BISCUIT
1    BREAD,MILK,BISCUIT,CORNFLAKES
2              BREAD,TEA,BOURNVITA
3             JAM,MAGGI,BREAD,MILK
4                MAGGI,TEA,BISCUIT
5              BREAD,TEA,BOURNVITA
6             MAGGI,TEA,CORNFLAKES
7          MAGGI,BREAD,TEA,BISCUIT
8              JAM,MAGGI,BREAD,TEA
9                       BREAD,MILK
10  COFFEE,COCK,BISCUIT,CORNFLAKES
11  COFFEE,COCK,BISCUIT,CORNFLAKES
12          COFFEE,SUGER,BOURNVITA
13               BREAD,COFFEE,COCK
14             BREAD,SUGER,BISCUIT
15         COFFEE,SUGER,CORNFLAKES
16           BREAD,SUGER,BOURNVITA
17              BREAD,COFFEE,SUGER
18              BREAD,COFFEE,SUGER
19      TEA,MILK,COFFEE,CORNFLAKES

In [5]:
df.columns

Index(['products'], dtype='object')

In [6]:
df.values

array([['MILK,BREAD,BISCUIT'],
       ['BREAD,MILK,BISCUIT,CORNFLAKES'],
       ['BREAD,TEA,BOURNVITA'],
       ['JAM,MAGGI,BREAD,MILK'],
       ['MAGGI,TEA,BISCUIT'],
       ['BREAD,TEA,BOURNVITA'],
       ['MAGGI,TEA,CORNFLAKES'],
       ['MAGGI,BREAD,TEA,BISCUIT'],
       ['JAM,MAGGI,BREAD,TEA'],
       ['BREAD,MILK'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,COCK,BISCUIT,CORNFLAKES'],
       ['COFFEE,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,COCK'],
       ['BREAD,SUGER,BISCUIT'],
       ['COFFEE,SUGER,CORNFLAKES'],
       ['BREAD,SUGER,BOURNVITA'],
       ['BREAD,COFFEE,SUGER'],
       ['BREAD,COFFEE,SUGER'],
       ['TEA,MILK,COFFEE,CORNFLAKES']], dtype=object)

In [7]:
data = list(df["products"].apply(lambda x:x.split(',')))
data

[['MILK', 'BREAD', 'BISCUIT'],
 ['BREAD', 'MILK', 'BISCUIT', 'CORNFLAKES'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['JAM', 'MAGGI', 'BREAD', 'MILK'],
 ['MAGGI', 'TEA', 'BISCUIT'],
 ['BREAD', 'TEA', 'BOURNVITA'],
 ['MAGGI', 'TEA', 'CORNFLAKES'],
 ['MAGGI', 'BREAD', 'TEA', 'BISCUIT'],
 ['JAM', 'MAGGI', 'BREAD', 'TEA'],
 ['BREAD', 'MILK'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'COCK', 'BISCUIT', 'CORNFLAKES'],
 ['COFFEE', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'COCK'],
 ['BREAD', 'SUGER', 'BISCUIT'],
 ['COFFEE', 'SUGER', 'CORNFLAKES'],
 ['BREAD', 'SUGER', 'BOURNVITA'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['BREAD', 'COFFEE', 'SUGER'],
 ['TEA', 'MILK', 'COFFEE', 'CORNFLAKES']]

In [9]:
from mlxtend.preprocessing import TransactionEncoder

In [10]:
te = TransactionEncoder()
te_data = te.fit(data).transform(data)
df = pd.DataFrame(te_data,columns=te.columns_)
df

,BISCUIT,BOURNVITA,BREAD,COCK,COFFEE,CORNFLAKES,JAM,MAGGI,MILK,SUGER,TEA
0,True,False,True,False,False,False,False,False,True,False,False
1,True,False,True,False,False,True,False,False,True,False,False
2,False,True,True,False,False,False,False,False,False,False,True
3,False,False,True,False,False,False,True,True,True,False,False
4,True,False,False,False,False,False,False,True,False,False,True
5,False,True,True,False,False,False,False,False,False,False,True
6,False,False,False,False,False,True,False,True,False,False,True
7,True,False,True,False,False,False,False,True,False,False,True
8,False,False,True,False,False,False,True,True,False,False,True
9,False,False,True,False,False,False,False,False,True,False,False
10,True,False,False,True,True,True,False,False,False,False,False
11,True,False,False,True,True,True,False,False,False,False,False
12,False,True,False,False,True,False,False,False,False,True,False
13,False,False,True,True,True,False,False,False,False,False,False
14,True,False,True,False,False,False,False,False,False,True,False
15,False,False,False,False,True,True,False,False,False,True,False
16,False,True,True,False,False,False,False,False,False,True,False
17,False,False,True,False,True,False,False,False,False,True,False
18,False,False,True,False,True,False,False,False,False,True,False
19,False,False,False,False,True,True,False,False,True,False,True

In [11]:
from mlxtend.frequent_patterns import apriori

In [12]:
df1 = apriori(df,min_support=0.01,use_colnames=True)
df1

    support                             itemsets
0      0.35                            (BISCUIT)
1      0.20                          (BOURNVITA)
2      0.65                              (BREAD)
3      0.15                               (COCK)
4      0.40                             (COFFEE)
5      0.30                         (CORNFLAKES)
6      0.10                                (JAM)
7      0.25                              (MAGGI)
8      0.25                               (MILK)
9      0.30                              (SUGER)
10     0.35                                (TEA)
11     0.20                     (BISCUIT, BREAD)
12     0.10                      (BISCUIT, COCK)
13     0.10                    (BISCUIT, COFFEE)
14     0.15                (BISCUIT, CORNFLAKES)
15     0.10                     (BISCUIT, MAGGI)
16     0.10                      (BISCUIT, MILK)
17     0.05                     (BISCUIT, SUGER)
18     0.10                       (BISCUIT, TEA)
19     0.15                   (BREAD, BOURNVITA)
20     0.05                  (COFFEE, BOURNVITA)
21     0.10                   (BOURNVITA, SUGER)
22     0.10                     (BOURNVITA, TEA)
23     0.05                        (COCK, BREAD)
24     0.15                      (COFFEE, BREAD)
25     0.05                  (CORNFLAKES, BREAD)
26     0.10                         (BREAD, JAM)
27     0.15                       (BREAD, MAGGI)
28     0.20                        (MILK, BREAD)
29     0.20                       (BREAD, SUGER)
..      ...                                  ...
53     0.10          (BISCUIT, CORNFLAKES, COCK)
54     0.10        (BISCUIT, COFFEE, CORNFLAKES)
55     0.05          (BISCUIT, CORNFLAKES, MILK)
56     0.10                (BISCUIT, MAGGI, TEA)
57     0.05            (BREAD, BOURNVITA, SUGER)
58     0.10              (BREAD, BOURNVITA, TEA)
59     0.05           (COFFEE, BOURNVITA, SUGER)
60     0.05                (COCK, COFFEE, BREAD)
61     0.10               (COFFEE, BREAD, SUGER)
62     0.05            (MILK, CORNFLAKES, BREAD)
63     0.10                  (BREAD, MAGGI, JAM)
64     0.05                   (MILK, BREAD, JAM)
65     0.05                    (BREAD, TEA, JAM)
66     0.05                 (MILK, BREAD, MAGGI)
67     0.10                  (BREAD, MAGGI, TEA)
68     0.10           (COFFEE, CORNFLAKES, COCK)
69     0.05           (MILK, COFFEE, CORNFLAKES)
70     0.05          (COFFEE, CORNFLAKES, SUGER)
71     0.05            (COFFEE, CORNFLAKES, TEA)
72     0.05                  (MILK, COFFEE, TEA)
73     0.05             (CORNFLAKES, MAGGI, TEA)
74     0.05              (MILK, CORNFLAKES, TEA)
75     0.05                   (MILK, MAGGI, JAM)
76     0.05                    (MAGGI, TEA, JAM)
77     0.05   (BISCUIT, CORNFLAKES, BREAD, MILK)
78     0.05         (BISCUIT, BREAD, MAGGI, TEA)
79     0.10  (BISCUIT, COFFEE, CORNFLAKES, COCK)
80     0.05            (MILK, BREAD, MAGGI, JAM)
81     0.05             (BREAD, MAGGI, TEA, JAM)
82     0.05      (MILK, COFFEE, CORNFLAKES, TEA)

[83 rows x 2 columns]

In [13]:
df1.sort_values(by="support",ascending=False)

    support                            itemsets
2      0.65                             (BREAD)
4      0.40                            (COFFEE)
0      0.35                           (BISCUIT)
10     0.35                               (TEA)
5      0.30                        (CORNFLAKES)
9      0.30                             (SUGER)
7      0.25                             (MAGGI)
8      0.25                              (MILK)
30     0.20                        (BREAD, TEA)
1      0.20                         (BOURNVITA)
28     0.20                       (MILK, BREAD)
35     0.20                     (COFFEE, SUGER)
29     0.20                      (BREAD, SUGER)
11     0.20                    (BISCUIT, BREAD)
33     0.20                (COFFEE, CORNFLAKES)
45     0.20                        (MAGGI, TEA)
14     0.15               (BISCUIT, CORNFLAKES)
31     0.15                      (COFFEE, COCK)
24     0.15                     (COFFEE, BREAD)
19     0.15                  (BREAD, BOURNVITA)
27     0.15                      (BREAD, MAGGI)
3      0.15                              (COCK)
40     0.10                   (CORNFLAKES, TEA)
58     0.10             (BREAD, BOURNVITA, TEA)
49     0.10              (BISCUIT, BREAD, MILK)
52     0.10             (BISCUIT, COFFEE, COCK)
53     0.10         (BISCUIT, CORNFLAKES, COCK)
54     0.10       (BISCUIT, COFFEE, CORNFLAKES)
56     0.10               (BISCUIT, MAGGI, TEA)
61     0.10              (COFFEE, BREAD, SUGER)
..      ...                                 ...
73     0.05            (CORNFLAKES, MAGGI, TEA)
74     0.05             (MILK, CORNFLAKES, TEA)
75     0.05                  (MILK, MAGGI, JAM)
76     0.05                   (MAGGI, TEA, JAM)
77     0.05  (BISCUIT, CORNFLAKES, BREAD, MILK)
78     0.05        (BISCUIT, BREAD, MAGGI, TEA)
80     0.05           (MILK, BREAD, MAGGI, JAM)
81     0.05            (BREAD, MAGGI, TEA, JAM)
72     0.05                 (MILK, COFFEE, TEA)
59     0.05          (COFFEE, BOURNVITA, SUGER)
62     0.05           (MILK, CORNFLAKES, BREAD)
60     0.05               (COCK, COFFEE, BREAD)
34     0.05                      (MILK, COFFEE)
39     0.05                 (CORNFLAKES, SUGER)
42     0.05                         (MILK, JAM)
43     0.05                          (TEA, JAM)
44     0.05                       (MILK, MAGGI)
25     0.05                 (CORNFLAKES, BREAD)
46     0.05                         (MILK, TEA)
47     0.05        (BISCUIT, CORNFLAKES, BREAD)
48     0.05             (BISCUIT, BREAD, MAGGI)
23     0.05                       (COCK, BREAD)
50     0.05             (BISCUIT, BREAD, SUGER)
51     0.05               (BISCUIT, BREAD, TEA)
20     0.05                 (COFFEE, BOURNVITA)
55     0.05         (BISCUIT, CORNFLAKES, MILK)
57     0.05           (BREAD, BOURNVITA, SUGER)
17     0.05                    (BISCUIT, SUGER)
37     0.05                 (CORNFLAKES, MAGGI)
82     0.05     (MILK, COFFEE, CORNFLAKES, TEA)

[83 rows x 2 columns]

In [14]:
df1['length'] = df1['itemsets'].apply(lambda x:len(x))
df1

    support                             itemsets  length
0      0.35                            (BISCUIT)       1
1      0.20                          (BOURNVITA)       1
2      0.65                              (BREAD)       1
3      0.15                               (COCK)       1
4      0.40                             (COFFEE)       1
5      0.30                         (CORNFLAKES)       1
6      0.10                                (JAM)       1
7      0.25                              (MAGGI)       1
8      0.25                               (MILK)       1
9      0.30                              (SUGER)       1
10     0.35                                (TEA)       1
11     0.20                     (BISCUIT, BREAD)       2
12     0.10                      (BISCUIT, COCK)       2
13     0.10                    (BISCUIT, COFFEE)       2
14     0.15                (BISCUIT, CORNFLAKES)       2
15     0.10                     (BISCUIT, MAGGI)       2
16     0.10                      (BISCUIT, MILK)       2
17     0.05                     (BISCUIT, SUGER)       2
18     0.10                       (BISCUIT, TEA)       2
19     0.15                   (BREAD, BOURNVITA)       2
20     0.05                  (COFFEE, BOURNVITA)       2
21     0.10                   (BOURNVITA, SUGER)       2
22     0.10                     (BOURNVITA, TEA)       2
23     0.05                        (COCK, BREAD)       2
24     0.15                      (COFFEE, BREAD)       2
25     0.05                  (CORNFLAKES, BREAD)       2
26     0.10                         (BREAD, JAM)       2
27     0.15                       (BREAD, MAGGI)       2
28     0.20                        (MILK, BREAD)       2
29     0.20                       (BREAD, SUGER)       2
..      ...                                  ...     ...
53     0.10          (BISCUIT, CORNFLAKES, COCK)       3
54     0.10        (BISCUIT, COFFEE, CORNFLAKES)       3
55     0.05          (BISCUIT, CORNFLAKES, MILK)       3
56     0.10                (BISCUIT, MAGGI, TEA)       3
57     0.05            (BREAD, BOURNVITA, SUGER)       3
58     0.10              (BREAD, BOURNVITA, TEA)       3
59     0.05           (COFFEE, BOURNVITA, SUGER)       3
60     0.05                (COCK, COFFEE, BREAD)       3
61     0.10               (COFFEE, BREAD, SUGER)       3
62     0.05            (MILK, CORNFLAKES, BREAD)       3
63     0.10                  (BREAD, MAGGI, JAM)       3
64     0.05                   (MILK, BREAD, JAM)       3
65     0.05                    (BREAD, TEA, JAM)       3
66     0.05                 (MILK, BREAD, MAGGI)       3
67     0.10                  (BREAD, MAGGI, TEA)       3
68     0.10           (COFFEE, CORNFLAKES, COCK)       3
69     0.05           (MILK, COFFEE, CORNFLAKES)       3
70     0.05          (COFFEE, CORNFLAKES, SUGER)       3
71     0.05            (COFFEE, CORNFLAKES, TEA)       3
72     0.05                  (MILK, COFFEE, TEA)       3
73     0.05             (CORNFLAKES, MAGGI, TEA)       3
74     0.05              (MILK, CORNFLAKES, TEA)       3
75     0.05                   (MILK, MAGGI, JAM)       3
76     0.05                    (MAGGI, TEA, JAM)       3
77     0.05   (BISCUIT, CORNFLAKES, BREAD, MILK)       4
78     0.05         (BISCUIT, BREAD, MAGGI, TEA)       4
79     0.10  (BISCUIT, COFFEE, CORNFLAKES, COCK)       4
80     0.05            (MILK, BREAD, MAGGI, JAM)       4
81     0.05             (BREAD, MAGGI, TEA, JAM)       4
82     0.05      (MILK, COFFEE, CORNFLAKES, TEA)       4

[83 rows x 3 columns]

In [18]:
df1[(df1['length']==2) & (df1['support']>=0.05)]

    support               itemsets  length
11     0.20       (BISCUIT, BREAD)       2
12     0.10        (BISCUIT, COCK)       2
13     0.10      (BISCUIT, COFFEE)       2
14     0.15  (BISCUIT, CORNFLAKES)       2
15     0.10       (BISCUIT, MAGGI)       2
16     0.10        (BISCUIT, MILK)       2
17     0.05       (BISCUIT, SUGER)       2
18     0.10         (BISCUIT, TEA)       2
19     0.15     (BREAD, BOURNVITA)       2
20     0.05    (COFFEE, BOURNVITA)       2
21     0.10     (BOURNVITA, SUGER)       2
22     0.10       (BOURNVITA, TEA)       2
23     0.05          (COCK, BREAD)       2
24     0.15        (COFFEE, BREAD)       2
25     0.05    (CORNFLAKES, BREAD)       2
26     0.10           (BREAD, JAM)       2
27     0.15         (BREAD, MAGGI)       2
28     0.20          (MILK, BREAD)       2
29     0.20         (BREAD, SUGER)       2
30     0.20           (BREAD, TEA)       2
31     0.15         (COFFEE, COCK)       2
32     0.10     (CORNFLAKES, COCK)       2
33     0.20   (COFFEE, CORNFLAKES)       2
34     0.05         (MILK, COFFEE)       2
35     0.20        (COFFEE, SUGER)       2
36     0.05          (COFFEE, TEA)       2
37     0.05    (CORNFLAKES, MAGGI)       2
38     0.10     (MILK, CORNFLAKES)       2
39     0.05    (CORNFLAKES, SUGER)       2
40     0.10      (CORNFLAKES, TEA)       2
41     0.10           (MAGGI, JAM)       2
42     0.05            (MILK, JAM)       2
43     0.05             (TEA, JAM)       2
44     0.05          (MILK, MAGGI)       2
45     0.20           (MAGGI, TEA)       2
46     0.05            (MILK, TEA)       2